"""Regenerate the mathematical outline as compact light-point coordinates.
Build-time only: matplotlib/numpy. The demo reads no font or external asset.
"""
from pathlib import Path
import math
import matplotlib
from matplotlib.textpath import TextPath

matplotlib.rcParams['mathtext.fontset'] = 'dejavuserif'
FORMULA = r'$U(P)=\frac{1}{i\lambda}\iint_{\Sigma} U(Q)\,\frac{e^{ikr}}{r}\,\left[\frac{1+\cos\theta}{2}\right]\,\mathrm{d}S$'
path = TextPath((0, 0), FORMULA, size=72)
bounds = path.get_extents()
scale = 1050 / bounds.width
points = []
for polygon in path.to_polygons():
    for a, b in zip(polygon, polygon[1:]):
        length = math.hypot(*(b-a)) * scale
        if length < .01:
            continue
        count = max(1, math.ceil(length/2.1))
        for j in range(count):
            v = a+(b-a)*(j/count)
            points.append((round((v[0]-bounds.xmin)*scale*4), round((v[1]-bounds.ymin)*scale*4)))
assert all(0 <= x < 65536 and 0 <= y < 65536 for x,y in points)
root = Path(__file__).resolve().parent.parent
out = '/* Generated by tools/make_formula.py. DejaVu / STIX math outlines; see licenses/FONTS.txt. */\n'
out += 'static const unsigned short equationShape[][2]={\n'
for i in range(0, len(points), 8):
    out += ','.join('{%d,%d}' % p for p in points[i:i+8])+',\n'
out += '};\n'
(root/'src/formula_points.h').write_text(out)
font_dir = Path(matplotlib.get_data_path())/'fonts/ttf'
(root/'licenses'/'FONTS.txt').write_text('DejaVu font notice\n\n'+(font_dir/'LICENSE_DEJAVU').read_text()+'\n\nSTIX font notice\n\n'+(font_dir/'LICENSE_STIX').read_text())
print('Formula:',len(points),'points,',len(points)*4,'bytes before compression')
